[build]
target = "index.html"
port = 1234


[serve.headers]
Cross-Origin-Opener-Policy = "same-origin"
# Cross-Origin-Embedder-Policy = "require-corp"
Content-Security-Policy = "worker-src 'self'; script-src 'self' 'wasm-unsafe-eval' 'unsafe-inline' https://cdn.tailwindcss.com; connect-src 'self' ws: wss:;"
# [serve]
# headers = { "Cross-Origin-Opener-Policy" = "same-origin", "Cross-Origin-Embedder-Policy" = "require-corp", "Content-Security-Policy" = "worker-src 'self'; script-src 'self' 'wasm-unsafe-eval' 'unsafe-inline'; connect-src 'self' ws: wss:;" }
